### ISSUE TITLE
How to Compile ??

### ISSUE THREAD

**Issue by pc8181** [pluginguy/plugins#2]
i just download and compile with VS2013 but it could not compiled
the error images below 
error c1083: cannot open include file 'PIDefines.h': No such file or directory

 
![image](https://user-images.githubusercontent.com/13380400/27534742-adda68c8-5a85-11e7-83d3-2dc3a66ea083.png)

**Comment by chimera15** [comment]
As I recall pidefines is part of the sdk...but even so there are more problems compiling this plugin.  I was never able to get it to fully compile from the source.   if you do let me know, or maybe we can try to figure it out together.

**Comment by chimera15** [comment]
There's a compiled version on an anime board.  I've been using that, been working fine.

**Comment by pluginguy** [comment]
The include paths probably don't match where you put the Photoshop SDK.  See project settings under C/C++ -> Additional Include Directories, where you should see a list of paths like "..\PhotoshopSDK\samplecode\Common".  (The library include path is also relative paths like this.)  The easiest thing to do is place the Photoshop SDK next to the source, so it looks like this:

greyc/GreycShop.vcxproj
greyc/(etc)
PhotoshopSDK/documentation.html
PhotoshopSDK/photoshopapi

I did it this way so several projects could use the same copy of the SDK and not have to hardcode an absolute path.  It builds for me in Visual Studio 2015.  (I don't know why they put important library headers inside "samplecode"...)

I have a very old version of the Photoshop SDK that hasn't changed since I wrote this (looks like CS4).  If it doesn't build with newer versions, you might also want to download that version of the SDK.

**Comment by pc8181** [comment]
thanks for your comments first step worked well but with errors please see the image

![image](https://user-images.githubusercontent.com/13380400/27571343-ad6737de-5b22-11e7-8719-354830328b9f.png)

**Comment by pluginguy** [comment]
Oh, that's a bug in the Photoshop SDK I worked around locally and forgot about.  I added a workaround in the code so it should work without changing the SDK code now.

**Comment by chimera15** [comment]
hmm, wow

**Comment by pc8181** [comment]
when will i get the updated version m eagerly waiting for download thanks for your contribution :)

**Comment by pc8181** [comment]
new error .... see the image

![image](https://user-images.githubusercontent.com/13380400/27621196-c5a48aa2-5bec-11e7-96c0-f7c3dfc6653a.png)

**Comment by pluginguy** [comment]
It's configured for VS2010.  Did you try the "Upgrade Solution" option that the message suggested?  That's probably what you need to do.

**Comment by pc8181** [comment]
i am using VS2013

**Comment by pc8181** [comment]
Have any Update please ..... m strucked

**Comment by pluginguy** [comment]
Look in project properties under General for "Platform Toolset" and set that to whatever the default is, probably just "Visual Studio 2013" (don't have that version anymore).

**Comment by pc8181** [comment]
thanQ so much bro it'z working but i got an another and final error may be .
see below image

![image](https://user-images.githubusercontent.com/13380400/27767205-929a557e-5f0c-11e7-9c4a-19d56f410d60.png)

**Comment by pc8181** [comment]
please help

**Comment by pluginguy** [comment]
That's an MFC header.  I don't know about VS2013, but in VS2015 they're in

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include

I don't know if your version has them included and you're just missing an include path, or if you need to install them from somewhere.  I don't *think* I needed to do anything extra with 2015...

**Comment by pc8181** [comment]
today i downloaded and try to compile i faced this below problem i think need Admin privileges to copy
.8bf to "c:\"

![image](https://user-images.githubusercontent.com/13380400/27853853-14450bba-6182-11e7-8258-c4ac489ecc51.png)

**Comment by pc8181** [comment]
thanks !! new downloaded compiled and create plugin files ..... thanks

but the above error always shown .... i know the reason but i duno how to resolve because i m a dot net
guy not c++  

what is the License ?

**Comment by pluginguy** [comment]
It's just trying to copy the plugin (nothing to do with C++), just give yourself write permissions to the plugin directory or disable the file copy (it's somewhere in the post build rules I think)...

The original greystoration license is linked at the bottom of each file where it applies (http://www.cecill.info/licences/Licence_CeCILL_V2-en.html).  My modifications are in the public domain, which includes all of the Photoshop plugin code.

**Comment by pc8181** [comment]
thanks
